baseURL = 'https://dancigrang.dev'
languageCode = 'en-us'
title = 'Dan Cigrang'
theme = 'cactus'
googleAnalytics = false

[params]
    colortheme = "dark"
    description = "Development and other notes"
    mainSectionTitle = "Blog"
    mainSection = "posts"
    showAllPostsOnHomePage = true
    postsOnHomePage = 5
    showProjectsList = false
    projectsUrl = "https://github.com/drc"
    rss = true
    showReadTime = true
    tocInline = true

# Main menu which appears below site header.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

# Social
[[params.social]]
    name = "github"
    link = "https://github.com/drc"

[[params.social]]
    name = "email"
    link = "dancigrang@protonmail.com" # no need for "mailto:" at the start

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/danielcigrang/"

[[params.social]]
    name = "spotify"
    link = "https://open.spotify.com/user/dj_bulbasaur"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "gruvbox"
        tabWidth = 4
