baseURL = 'http://drc.github.io/'
languageCode = 'en-us'
title = 'Dan Cigrang'
theme = 'cactus'

[params]
    colortheme = "dark"
    description = "Description update"
    mainSectionTitle = "Blog"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    showProjectsList = true
    projectsUrl = "https://github.com/drc"
    rss = true

# Main menu which appears below site header.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

# Social
[[params.social]]
    name = "github"
    link = "https://github.com/drc"

[[params.social]]
    name = "email"
    link = "dancigrang@protonmail.com" # no need for "mailto:" at the start

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dancigrang/"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "gruvbox"
        tabWidth = 4